<template>
  <div class="exam-paper-management">
    <el-tabs v-model="activeTab">
      <el-tab-pane label="试卷列表" name="list">
        <el-card>
          <template #header>
            <div class="card-header">
              <span>试卷管理</span>
              <div class="header-actions">
                <el-select v-model="filterCourseId" placeholder="选择课程" clearable style="width: 180px; margin-right: 10px">
                  <el-option
                    v-for="course in courses"
                    :key="course.id"
                    :label="course.courseName"
                    :value="course.id"
                  />
                </el-select>
                <el-select v-model="filterStatus" placeholder="试卷状态" clearable style="width: 140px; margin-right: 10px">
                  <el-option
                    v-for="status in paperStatuses"
                    :key="status.value"
                    :label="status.label"
                    :value="status.value"
                  />
                </el-select>
                <el-dropdown @command="handleCreateCommand">
                  <el-button type="primary">
                    <el-icon><Plus /></el-icon>
                    新建试卷
                    <el-icon class="el-icon--right"><ArrowDown /></el-icon>
                  </el-button>
                  <template #dropdown>
                    <el-dropdown-menu>
                      <el-dropdown-item command="auto">
                        <el-icon><MagicStick /></el-icon>
                        自动组卷
                      </el-dropdown-item>
                      <el-dropdown-item command="manual">
                        <el-icon><EditPen /></el-icon>
                        手动组卷
                      </el-dropdown-item>
                    </el-dropdown-menu>
                  </template>
                </el-dropdown>
              </div>
            </div>
          </template>

          <el-table :data="filteredPapers" v-loading="loading" stripe>
            <el-table-column prop="title" label="试卷标题" min-width="200" />
            <el-table-column prop="courseName" label="所属课程" width="120" />
            <el-table-column prop="totalScore" label="总分" width="80" />
            <el-table-column prop="questionCount" label="题目数" width="80" />
            <el-table-column prop="duration" label="时长(分钟)" width="100" />
            <el-table-column prop="creationMethodName" label="组卷方式" width="100">
              <template #default="{ row }">
                <el-tag :type="row.creationMethod === 'AUTO' ? 'primary' : 'success'" size="small">
                  {{ row.creationMethodName }}
                </el-tag>
              </template>
            </el-table-column>
            <el-table-column prop="statusName" label="状态" width="100">
              <template #default="{ row }">
                <el-tag :type="getStatusType(row.status)" size="small">
                  {{ row.statusName }}
                </el-tag>
              </template>
            </el-table-column>
            <el-table-column label="操作" width="220" fixed="right">
              <template #default="{ row }">
                <el-button type="primary" link @click="viewPaper(row)">查看</el-button>
                <el-button
                  v-if="row.status === 'DRAFT'"
                  type="warning"
                  link
                  @click="editPaper(row)"
                >
                  编辑
                </el-button>
                <el-button
                  v-if="row.status === 'DRAFT' && row.questionCount > 0"
                  type="success"
                  link
                  @click="publishPaper(row)"
                >
                  发布
                </el-button>
                <el-button
                  v-if="row.status === 'DRAFT'"
                  type="danger"
                  link
                  @click="deletePaper(row)"
                >
                  删除
                </el-button>
              </template>
            </el-table-column>
          </el-table>

          <el-empty v-if="!loading && examPapers.length === 0" description="暂无试卷" />
        </el-card>
      </el-tab-pane>
    </el-tabs>

    <el-dialog
      v-model="autoGenerateDialogVisible"
      title="自动组卷"
      width="700px"
    >
      <el-form :model="autoConfig" label-width="120px">
        <el-form-item label="所属课程">
          <el-select v-model="autoConfig.courseId" placeholder="选择课程（可选）" style="width: 100%">
            <el-option
              v-for="course in courses"
              :key="course.id"
              :label="course.courseName"
              :value="course.id"
            />
          </el-select>
        </el-form-item>
        <el-form-item label="试卷标题">
          <el-input v-model="autoConfig.title" placeholder="请输入试卷标题（留空则自动生成）" />
        </el-form-item>
        <el-form-item label="考试时长">
          <el-input-number v-model="autoConfig.duration" :min="10" :max="300" />
          <span style="margin-left: 10px; color: #909399">分钟</span>
        </el-form-item>
        <el-divider content-position="left">题目配置</el-divider>
        <div v-for="(config, index) in autoConfig.typeConfigs" :key="index" class="type-config-item">
          <el-row :gutter="10" align="middle">
            <el-col :span="6">
              <el-select v-model="config.type" placeholder="题目类型" style="width: 100%">
                <el-option
                  v-for="type in questionTypes"
                  :key="type.value"
                  :label="type.label"
                  :value="type.value"
                />
              </el-select>
            </el-col>
            <el-col :span="5">
              <el-input-number
                v-model="config.count"
                :min="1"
                :max="100"
                placeholder="数量"
                style="width: 100%"
              />
              <span style="margin-left: 5px; color: #909399">题</span>
            </el-col>
            <el-col :span="5">
              <el-input-number
                v-model="config.scorePerQuestion"
                :min="0.5"
                :max="50"
                :step="0.5"
                placeholder="每题分数"
                style="width: 100%"
              />
              <span style="margin-left: 5px; color: #909399">分/题</span>
            </el-col>
            <el-col :span="5">
              <el-select v-model="config.difficulty" placeholder="难度（可选）" clearable style="width: 100%">
                <el-option label="简单" value="简单" />
                <el-option label="中等" value="中等" />
                <el-option label="困难" value="困难" />
              </el-select>
            </el-col>
            <el-col :span="3">
              <el-button
                type="danger"
                link
                @click="removeTypeConfig(index)"
                v-if="autoConfig.typeConfigs.length > 1"
              >
                删除
              </el-button>
            </el-col>
          </el-row>
        </div>
        <el-button type="primary" link @click="addTypeConfig" style="margin-top: 10px">
          <el-icon><Plus /></el-icon>
          添加题目类型
        </el-button>
        <el-divider content-position="left">预计统计</el-divider>
        <div class="summary-info">
          <div>
            <span class="label">预计题目数：</span>
            <span class="value">{{ totalAutoQuestions }} 题</span>
          </div>
          <div>
            <span class="label">预计总分：</span>
            <span class="value">{{ totalAutoScore }} 分</span>
          </div>
        </div>
      </el-form>
      <template #footer>
        <el-button @click="autoGenerateDialogVisible = false">取消</el-button>
        <el-button type="primary" @click="submitAutoGenerate" :loading="generating">
          开始组卷
        </el-button>
      </template>
    </el-dialog>

    <el-dialog
      v-model="manualCreateDialogVisible"
      :title="isEditing ? '编辑试卷' : '手动组卷'"
      width="900px"
    >
      <el-form :model="paperForm" label-width="100px">
        <el-row :gutter="20">
          <el-col :span="12">
            <el-form-item label="试卷标题" required>
              <el-input v-model="paperForm.title" placeholder="请输入试卷标题" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="所属课程">
              <el-select v-model="paperForm.courseId" placeholder="选择课程（可选）" style="width: 100%">
                <el-option
                  v-for="course in courses"
                  :key="course.id"
                  :label="course.courseName"
                  :value="course.id"
                />
              </el-select>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row :gutter="20">
          <el-col :span="12">
            <el-form-item label="考试时长">
              <el-input-number v-model="paperForm.duration" :min="10" :max="300" />
              <span style="margin-left: 10px; color: #909399">分钟</span>
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="试卷描述">
              <el-input v-model="paperForm.description" placeholder="试卷描述（可选）" />
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>

      <el-divider content-position="left">
        已选题目 ({{ selectedQuestions.length }} 题，共 {{ selectedTotalScore }} 分)
        <el-button type="primary" link @click="openQuestionSelector" style="margin-left: 20px">
          <el-icon><Plus /></el-icon>
          添加题目
        </el-button>
      </el-divider>

      <el-table :data="selectedQuestions" stripe size="small" style="margin-top: 10px">
        <el-table-column type="index" label="序号" width="60" />
        <el-table-column prop="typeName" label="类型" width="80" />
        <el-table-column prop="content" label="题目内容" min-width="250" show-overflow-tooltip />
        <el-table-column width="120">
          <template #header>
            <span>每题分数</span>
          </template>
          <template #default="{ row, $index }">
            <el-input-number
              v-model="row.score"
              :min="0.5"
              :max="100"
              :step="0.5"
              size="small"
              style="width: 100px"
              @change="updateSelectedQuestionScore($index, row.score)"
            />
          </template>
        </el-table-column>
        <el-table-column label="操作" width="80">
          <template #default="{ row, $index }">
            <el-button type="danger" link @click="removeSelectedQuestion($index)">
              移除
            </el-button>
          </template>
        </el-table-column>
      </el-table>

      <el-empty v-if="selectedQuestions.length === 0" description="暂无题目，请点击上方添加题目" :image-size="80" />

      <template #footer>
        <el-button @click="manualCreateDialogVisible = false">取消</el-button>
        <el-button type="primary" @click="submitManualPaper" :loading="saving">
          保存试卷
        </el-button>
      </template>
    </el-dialog>

    <el-dialog
      v-model="questionSelectorVisible"
      title="选择题目"
      width="1000px"
    >
      <el-card shadow="never" style="margin-bottom: 16px">
        <el-row :gutter="16">
          <el-col :span="6">
            <el-select v-model="selectorFilter.courseId" placeholder="选择课程" clearable style="width: 100%">
              <el-option
                v-for="course in courses"
                :key="course.id"
                :label="course.courseName"
                :value="course.id"
              />
            </el-select>
          </el-col>
          <el-col :span="5">
            <el-select v-model="selectorFilter.type" placeholder="题目类型" clearable style="width: 100%">
              <el-option
                v-for="type in questionTypes"
                :key="type.value"
                :label="type.label"
                :value="type.value"
              />
            </el-select>
          </el-col>
          <el-col :span="5">
            <el-select v-model="selectorFilter.difficulty" placeholder="难度" clearable style="width: 100%">
              <el-option label="简单" value="简单" />
              <el-option label="中等" value="中等" />
              <el-option label="困难" value="困难" />
            </el-select>
          </el-col>
          <el-col :span="4">
            <el-button type="primary" @click="searchQuestions">搜索</el-button>
          </el-col>
        </el-row>
      </el-card>

      <el-table
        :data="selectorQuestions"
        v-loading="selectorLoading"
        stripe
        @selection-change="handleSelectorSelectionChange"
      >
        <el-table-column type="selection" width="55" />
        <el-table-column prop="typeName" label="类型" width="80" />
        <el-table-column prop="content" label="题目内容" min-width="300" show-overflow-tooltip />
        <el-table-column prop="courseName" label="课程" width="100" />
        <el-table-column prop="score" label="默认分值" width="80" />
        <el-table-column prop="difficulty" label="难度" width="80">
          <template #default="{ row }">
            <el-tag :type="getDifficultyType(row.difficulty)" size="small">
              {{ row.difficulty || '-' }}
            </el-tag>
          </template>
        </el-table-column>
      </el-table>

      <div style="margin-top: 16px; text-align: right">
        <span style="margin-right: 16px">已选择 {{ selectorSelected.length }} 题</span>
        <el-button @click="questionSelectorVisible = false">取消</el-button>
        <el-button type="primary" @click="confirmSelectorSelection" :disabled="selectorSelected.length === 0">
          确认选择
        </el-button>
      </div>
    </el-dialog>

    <el-dialog
      v-model="detailDialogVisible"
      title="试卷详情"
      width="800px"
    >
      <el-descriptions :column="2" border v-if="currentPaper">
        <el-descriptions-item label="试卷标题">{{ currentPaper.title }}</el-descriptions-item>
        <el-descriptions-item label="所属课程">{{ currentPaper.courseName || '未关联课程' }}</el-descriptions-item>
        <el-descriptions-item label="总分">{{ currentPaper.totalScore }} 分</el-descriptions-item>
        <el-descriptions-item label="题目数">{{ currentPaper.questionCount }} 题</el-descriptions-item>
        <el-descriptions-item label="考试时长">{{ currentPaper.duration }} 分钟</el-descriptions-item>
        <el-descriptions-item label="组卷方式">
          <el-tag :type="currentPaper.creationMethod === 'AUTO' ? 'primary' : 'success'">
            {{ currentPaper.creationMethodName }}
          </el-tag>
        </el-descriptions-item>
        <el-descriptions-item label="状态">
          <el-tag :type="getStatusType(currentPaper.status)">
            {{ currentPaper.statusName }}
          </el-tag>
        </el-descriptions-item>
        <el-descriptions-item label="创建时间">{{ currentPaper.createdAt }}</el-descriptions-item>
      </el-descriptions>

      <el-divider content-position="left">题目列表</el-divider>

      <el-table :data="currentPaper.questions" stripe size="small" v-if="currentPaper.questions">
        <el-table-column type="index" label="序号" width="60" />
        <el-table-column prop="typeName" label="类型" width="80" />
        <el-table-column prop="content" label="题目内容" min-width="250" show-overflow-tooltip />
        <el-table-column prop="score" label="分值" width="80" />
        <el-table-column prop="difficulty" label="难度" width="80">
          <template #default="{ row }">
            <el-tag :type="getDifficultyType(row.difficulty)" size="small">
              {{ row.difficulty || '-' }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column label="答案" width="100" show-overflow-tooltip>
          <template #default="{ row }">
            {{ row.answer }}
          </template>
        </el-table-column>
      </el-table>

      <el-empty v-else description="暂无题目" :image-size="80" />
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import {
  Plus, ArrowDown, MagicStick, EditPen
} from '@element-plus/icons-vue'
import { getTeacherCourses } from '@/api/courses'
import {
  getTeacherExamPapers,
  getExamPaperById,
  createExamPaper,
  updateExamPaper,
  deleteExamPaper,
  publishExamPaper,
  autoGenerateExamPaper,
  getExamPaperStatuses,
  getCreationMethods
} from '@/api/examPapers'
import { getTeacherQuestions, getQuestionTypes } from '@/api/questions'

const activeTab = ref('list')
const courses = ref([])
const examPapers = ref([])
const questionTypes = ref([])
const paperStatuses = ref([])
const creationMethods = ref([])
const loading = ref(false)

const filterCourseId = ref(null)
const filterStatus = ref(null)

const filteredPapers = computed(() => {
  let result = examPapers.value
  if (filterCourseId.value) {
    result = result.filter(p => p.courseId === filterCourseId.value)
  }
  if (filterStatus.value) {
    result = result.filter(p => p.status === filterStatus.value)
  }
  return result
})

const autoGenerateDialogVisible = ref(false)
const generating = ref(false)
const autoConfig = ref({
  courseId: null,
  title: '',
  duration: 120,
  typeConfigs: [
    { type: 'SINGLE_CHOICE', count: 10, scorePerQuestion: 2, difficulty: '' }
  ]
})

const totalAutoQuestions = computed(() => {
  return autoConfig.value.typeConfigs.reduce((sum, c) => sum + (c.count || 0), 0)
})

const totalAutoScore = computed(() => {
  return autoConfig.value.typeConfigs.reduce((sum, c) => sum + (c.count || 0) * (c.scorePerQuestion || 0), 0)
})

const manualCreateDialogVisible = ref(false)
const isEditing = ref(false)
const currentPaperId = ref(null)
const saving = ref(false)
const paperForm = ref({
  title: '',
  description: '',
  courseId: null,
  duration: 120,
  totalScore: 0
})

const selectedQuestions = ref([])
const selectedTotalScore = computed(() => {
  return selectedQuestions.value.reduce((sum, q) => sum + (q.score || 0), 0)
})

const questionSelectorVisible = ref(false)
const selectorLoading = ref(false)
const selectorQuestions = ref([])
const selectorSelected = ref([])
const selectorFilter = ref({
  courseId: null,
  type: null,
  difficulty: null
})

const detailDialogVisible = ref(false)
const currentPaper = ref(null)

const getStatusType = (status) => {
  const map = {
    DRAFT: 'info',
    PUBLISHED: 'success',
    ARCHIVED: 'warning'
  }
  return map[status] || 'info'
}

const getDifficultyType = (difficulty) => {
  const map = {
    '简单': 'success',
    '中等': 'warning',
    '困难': 'danger'
  }
  return map[difficulty] || 'info'
}

const fetchCourses = async () => {
  try {
    const res = await getTeacherCourses()
    courses.value = res.data
  } catch (error) {
    console.error(error)
  }
}

const fetchQuestionTypes = async () => {
  try {
    const res = await getQuestionTypes()
    questionTypes.value = res.data
  } catch (error) {
    console.error(error)
  }
}

const fetchPaperStatuses = async () => {
  try {
    const res = await getExamPaperStatuses()
    paperStatuses.value = res.data
  } catch (error) {
    console.error(error)
  }
}

const fetchExamPapers = async () => {
  loading.value = true
  try {
    const res = await getTeacherExamPapers(filterCourseId.value)
    examPapers.value = res.data
  } catch (error) {
    console.error(error)
    ElMessage.error('获取试卷列表失败')
  } finally {
    loading.value = false
  }
}

const handleCreateCommand = (command) => {
  if (command === 'auto') {
    openAutoGenerateDialog()
  } else {
    openManualCreateDialog()
  }
}

const openAutoGenerateDialog = () => {
  autoConfig.value = {
    courseId: null,
    title: '',
    duration: 120,
    typeConfigs: [
      { type: 'SINGLE_CHOICE', count: 10, scorePerQuestion: 2, difficulty: '' }
    ]
  }
  autoGenerateDialogVisible.value = true
}

const addTypeConfig = () => {
  autoConfig.value.typeConfigs.push({
    type: 'SINGLE_CHOICE',
    count: 5,
    scorePerQuestion: 2,
    difficulty: ''
  })
}

const removeTypeConfig = (index) => {
  autoConfig.value.typeConfigs.splice(index, 1)
}

const submitAutoGenerate = async () => {
  if (autoConfig.value.typeConfigs.length === 0) {
    ElMessage.warning('请至少配置一种题目类型')
    return
  }

  const validConfigs = autoConfig.value.typeConfigs.filter(c => c.type && c.count > 0 && c.scorePerQuestion > 0)
  if (validConfigs.length === 0) {
    ElMessage.warning('请完整配置题目类型、数量和分值')
    return
  }

  generating.value = true
  try {
    const config = {
      courseId: autoConfig.value.courseId,
      totalScore: totalAutoScore.value,
      duration: autoConfig.value.duration,
      typeConfigs: validConfigs
    }

    const res = await autoGenerateExamPaper(config)
    
    if (autoConfig.value.title) {
      await updateExamPaper(res.data.id, {
        title: autoConfig.value.title,
        courseId: autoConfig.value.courseId
      })
    }

    ElMessage.success('自动组卷成功')
    autoGenerateDialogVisible.value = false
    fetchExamPapers()
  } catch (error) {
    console.error(error)
    ElMessage.error(error.response?.data?.message || '组卷失败')
  } finally {
    generating.value = false
  }
}

const openManualCreateDialog = () => {
  isEditing.value = false
  currentPaperId.value = null
  paperForm.value = {
    title: '',
    description: '',
    courseId: null,
    duration: 120,
    totalScore: 0
  }
  selectedQuestions.value = []
  manualCreateDialogVisible.value = true
}

const editPaper = async (row) => {
  try {
    const res = await getExamPaperById(row.id)
    currentPaperId.value = row.id
    isEditing.value = true
    paperForm.value = {
      title: res.data.title,
      description: res.data.description || '',
      courseId: res.data.courseId,
      duration: res.data.duration,
      totalScore: res.data.totalScore
    }
    selectedQuestions.value = res.data.questions ? res.data.questions.map((q, index) => ({
      ...q,
      sortOrder: index + 1
    })) : []
    manualCreateDialogVisible.value = true
  } catch (error) {
    console.error(error)
    ElMessage.error('获取试卷详情失败')
  }
}

const openQuestionSelector = () => {
  selectorFilter.value = {
    courseId: paperForm.value.courseId,
    type: null,
    difficulty: null
  }
  selectorQuestions.value = []
  selectorSelected.value = []
  questionSelectorVisible.value = true
  searchQuestions()
}

const searchQuestions = async () => {
  selectorLoading.value = true
  try {
    const res = await getTeacherQuestions(selectorFilter.value.courseId)
    let questions = res.data

    if (selectorFilter.value.type) {
      questions = questions.filter(q => q.type === selectorFilter.value.type)
    }
    if (selectorFilter.value.difficulty) {
      questions = questions.filter(q => q.difficulty === selectorFilter.value.difficulty)
    }

    const selectedIds = new Set(selectedQuestions.value.map(q => q.questionId))
    selectorQuestions.value = questions.filter(q => !selectedIds.has(q.id))
  } catch (error) {
    console.error(error)
    ElMessage.error('获取题目列表失败')
  } finally {
    selectorLoading.value = false
  }
}

const handleSelectorSelectionChange = (selection) => {
  selectorSelected.value = selection
}

const confirmSelectorSelection = () => {
  const newQuestions = selectorSelected.value.map((q, index) => ({
    questionId: q.id,
    id: q.id,
    type: q.type,
    typeName: q.typeName,
    content: q.content,
    options: q.options,
    answer: q.answer,
    explanation: q.explanation,
    difficulty: q.difficulty,
    score: q.score,
    sortOrder: selectedQuestions.value.length + index + 1
  }))
  selectedQuestions.value = [...selectedQuestions.value, ...newQuestions]
  questionSelectorVisible.value = false
}

const removeSelectedQuestion = (index) => {
  selectedQuestions.value.splice(index, 1)
  selectedQuestions.value.forEach((q, i) => {
    q.sortOrder = i + 1
  })
}

const updateSelectedQuestionScore = (index, score) => {
  if (selectedQuestions.value[index]) {
    selectedQuestions.value[index].score = score
  }
}

const submitManualPaper = async () => {
  if (!paperForm.value.title?.trim()) {
    ElMessage.warning('请输入试卷标题')
    return
  }

  saving.value = true
  try {
    const data = {
      title: paperForm.value.title,
      description: paperForm.value.description,
      courseId: paperForm.value.courseId,
      duration: paperForm.value.duration,
      totalScore: selectedTotalScore.value,
      questionCount: selectedQuestions.value.length,
      questions: selectedQuestions.value.map((q, index) => ({
        questionId: q.questionId,
        sortOrder: index + 1,
        score: q.score
      }))
    }

    if (isEditing.value && currentPaperId.value) {
      await updateExamPaper(currentPaperId.value, data)
      ElMessage.success('更新成功')
    } else {
      await createExamPaper(data)
      ElMessage.success('创建成功')
    }

    manualCreateDialogVisible.value = false
    fetchExamPapers()
  } catch (error) {
    console.error(error)
    ElMessage.error(error.response?.data?.message || '操作失败')
  } finally {
    saving.value = false
  }
}

const viewPaper = async (row) => {
  try {
    const res = await getExamPaperById(row.id)
    currentPaper.value = res.data
    detailDialogVisible.value = true
  } catch (error) {
    console.error(error)
    ElMessage.error('获取试卷详情失败')
  }
}

const publishPaper = async (row) => {
  try {
    await ElMessageBox.confirm('确定要发布该试卷吗？发布后将无法修改。', '确认发布', {
      confirmButtonText: '确定',
      cancelButtonText: '取消',
      type: 'warning'
    })

    await publishExamPaper(row.id)
    ElMessage.success('发布成功')
    fetchExamPapers()
  } catch (error) {
    if (error !== 'cancel') {
      console.error(error)
      ElMessage.error(error.response?.data?.message || '发布失败')
    }
  }
}

const deletePaper = async (row) => {
  try {
    await ElMessageBox.confirm('确定要删除该试卷吗？删除后无法恢复。', '确认删除', {
      confirmButtonText: '确定',
      cancelButtonText: '取消',
      type: 'warning'
    })

    await deleteExamPaper(row.id)
    ElMessage.success('删除成功')
    fetchExamPapers()
  } catch (error) {
    if (error !== 'cancel') {
      console.error(error)
      ElMessage.error(error.response?.data?.message || '删除失败')
    }
  }
}

onMounted(() => {
  fetchCourses()
  fetchQuestionTypes()
  fetchPaperStatuses()
  fetchExamPapers()
})
</script>

<style scoped>
.exam-paper-management {
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.header-actions {
  display: flex;
  align-items: center;
}

.type-config-item {
  padding: 10px 0;
  border-bottom: 1px solid #ebeef5;
}

.type-config-item:last-child {
  border-bottom: none;
}

.summary-info {
  display: flex;
  gap: 40px;
  padding: 10px 0;
}

.summary-info .label {
  color: #909399;
}

.summary-info .value {
  font-weight: 600;
  font-size: 16px;
  color: #409eff;
}

:deep(.el-tabs__content) {
  padding-top: 16px;
}
</style>
